### ISSUE TITLE
Variables not set

### ISSUE THREAD

**Issue by secure-xxx** [hiqdev/hipanel-core#219]
WARNING: The HOSTS variable is not set. Defaulting to a blank string.
WARNING: The LETSENCRYPT_STANDALONE_CERTS variable is not set. Defaulting to a blank string.
WARNING: The API_HOSTS_LINE variable is not set. Defaulting to a blank string.
WARNING: The ENV variable is not set. Defaulting to a blank string.
WARNING: The HIAPI_DIST variable is not set. Defaulting to a blank string.
WARNING: The REAL_IP variable is not set. Defaulting to a blank string.

**Comment by SilverFire** [comment]
Define these variables in `.env`
